### ISSUE TITLE
Facebook icon in header does not work

### ISSUE THREAD

**Issue by purplyrocky** [EditLLC/client-faceandskin#1]
OS: Windows 8
Browser: Chrome

Icon just doesn't take you to the facebook page. When you hover over it, you can see it isn't even recognizing that it clickable.

**Comment by rodneystrong** [comment]
for this, try removing the facebook img from within the <address> tag. 
this would also make sense semantically since the <address> tag is meant for physical address according to the spec: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address

**Comment by purplyrocky** [comment]
Unfortunately, I tried that last night and it did not fix the problem :(

**Comment by rodneystrong** [comment]
interesting... try forgoing the <address> tag and put it in a <div> with a
class of 'address'

--
Curious?
twitter.com/rodneystrong
<http://t.sidekickopen03.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LPX_nW1qg5781p1gBxW64QWwH56dP5rf2vVXml02?t=http%3A%2F%2Fj.mp%2FdPPtuu&si=5624745914007552&pi=414c3bbe-888c-4938-bd9d-c09f44e3bc5b>

**Comment by purplyrocky** [comment]
it works if you take it out of the column completely. Would that be a bad idea though?

**Comment by rodneystrong** [comment]
wait a minute.. that doesn't make sense.. that tells me there's an outer container or adjacent container that's affecting this.. let me take another look. 
pulling that section out of the columns defeats the purpose of bootstrap

**Comment by purplyrocky** [comment]
Could it be the page-header div?

**Comment by rodneystrong** [comment]
found it. most likely at least.
you're not using the bootstrap  'row' classes. when it comes to bootstrap, you have to have the 'col-sm-whatever' classes nested inside a <div class="row"> tag, always. 
let me know if you need a bit more clarity, but i looked at the rest of your markup and you're following the rules correctly. just not on this part.

**Comment by rodneystrong** [comment]
@purplyrocky sorry i realiezd i used HTML inside a markdown comment, thus actually rendering the '< div class='row' > ' markup instead of just displaying it as text. please re-read my previous comment

**Comment by purplyrocky** [comment]
It's fine, I understood what you meant. I added the row inside the container just outside the column divs and moved the icon outside the address tag.  Still does not work

**Comment by rodneystrong** [comment]
hmm... i'm not seeing these changes in the commit history. could you do me quick favor and make the class = 'row' change please and push it to master + gh-pages?

**Comment by purplyrocky** [comment]
here you go 0c43d20d74d49879c3008bc9aa40943eb1ed3a95

**Comment by rodneystrong** [comment]
@purplyrocky awesome, thanks for that. Gonna check this out before 7p today.

**Comment by purplyrocky** [comment]
I fixed it! :D bcf8bfb6e99cd12c4fb930c7fc285d47d85fc934
It's already been pushed to gh-pages and master also uploaded to the ftp
