### ISSUE TITLE
GA Tracking code

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-faceandskin#2]
Yo! Got the GA tracking code for Leta About face and skin. 

When you have a moment, could you please put this code at the bottom of all pages of aboutfaceandskin.com ? 

Update both the master and gh-pages branches and THEN upload to the FTP

**Comment by purplyrocky** [comment]
@rodneystrong Where the code be?

**Comment by rodneystrong** [comment]
Oh my goodness SUPER fail alex... T_T)  Sorry about that. Here it is: 


<script>

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){

(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),

m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)

})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-64283737-1', 'auto');

ga('send', 'pageview');

</script>

**Comment by purplyrocky** [comment]
Done.
